// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolunteerService.Persistence.DbContexts;

#nullable disable

namespace VolunteerService.Persistence.Migrations
{
    [DbContext(typeof(VolunteersDbContext))]
    [Migration("20250427213358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolunteerService.Domain.Entities.Volunteer", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RatingNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGID")
                        .HasColumnType("uuid");

                    b.HasKey("GID");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersDistricts", b =>
                {
                    b.Property<Guid>("GID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictGID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerGID")
                        .HasColumnType("uuid");

                    b.HasKey("GID");

                    b.HasIndex("VolunteerGID", "DistrictGID")
                        .IsUnique();

                    b.ToTable("VolunteersDistricts");
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersEvents", b =>
                {
                    b.Property<Guid>("GID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventGID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerGID")
                        .HasColumnType("uuid");

                    b.HasKey("GID");

                    b.HasIndex("VolunteerGID", "EventGID")
                        .IsUnique();

                    b.ToTable("VolunteersEvents");
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersGroups", b =>
                {
                    b.Property<Guid>("GID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupGID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerGID")
                        .HasColumnType("uuid");

                    b.HasKey("GID");

                    b.HasIndex("VolunteerGID", "GroupGID")
                        .IsUnique();

                    b.ToTable("VolunteersGroups");
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersDistricts", b =>
                {
                    b.HasOne("VolunteerService.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersEvents", b =>
                {
                    b.HasOne("VolunteerService.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerService.Domain.Entities.VolunteersGroups", b =>
                {
                    b.HasOne("VolunteerService.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
