// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtilsService.Persistence.DbContexts;

#nullable disable

namespace UtilsService.Persistence.Migrations
{
    [DbContext(typeof(UtilsDbContext))]
    [Migration("20250316114144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtilsService.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GID");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("UtilsService.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GID");

                    b.ToTable("MeasurementUnits");
                });

            modelBuilder.Entity("UtilsService.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GID");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("UtilsService.Domain.Entities.ResourceMeasurementUnit", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceGID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitGID")
                        .HasColumnType("uuid");

                    b.HasKey("GID");

                    b.HasIndex("ResourceGID");

                    b.HasIndex("UnitGID");

                    b.ToTable("ResourceMeasurementUnits");
                });

            modelBuilder.Entity("UtilsService.Domain.Entities.ResourceMeasurementUnit", b =>
                {
                    b.HasOne("UtilsService.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilsService.Domain.Entities.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
