services:
  utilsservice:
    container_name: utilsservice
    build:
      context: ./UtilsService/
      dockerfile: Dockerfile
    ports:
      - "7089:8080" 
      - "5031:8080"
    depends_on:
      - authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
  authservice:
    container_name: authservice
    build:
      context: ./AuthService/
      dockerfile: Dockerfile
    ports:
      - "5107:8080" 
      - "7224:8080"
    depends_on:
      - postgresql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
  operationsservice:
    container_name: operationsservice
    build:
      context: ./OperationsService/
      dockerfile: Dockerfile
    ports:
      - "7088:8080" 
      - "5160:8080"
    depends_on:
      - authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
  volunteerservice:
    container_name: volunteerservice
    build:
      context: ./VolunteerService/
      dockerfile: Dockerfile
    ports:
      - "7105:8080" 
      - "5083:8080"
    depends_on:
      - authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
  postgresql-server:
    container_name: postgresql-server
    build:
      context: .
      dockerfile: sql.Dockerfile
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge